name: Run tests

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/test.yml"
      - "**.py"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/test.yml"
      - "**.py"

env:
  FORCE_COLOR: '1'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install poetry
        run: |
          pipx install poetry
          poetry env use ${{ matrix.python }}
      - name: Install dependencies
        run: poetry install
      - name: Run all tests
        run: poetry run pytest
